# Generated by Django 4.0.4 on 2023-05-02 06:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.PositiveIntegerField(default=1000)),
                ('memory_limit', models.PositiveIntegerField(default=256)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('difficulty', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Basic'), (3, 'Normal'), (4, 'Medium'), (5, 'Advanced'), (6, 'Hard'), (7, 'Extremal')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='backend.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.IntegerField(choices=[(-2, 'In Queue'), (-1, 'Running'), (0, 'Judgement Failed'), (1, 'Accepted'), (2, 'Wrong Answer'), (3, 'Time Limit Exceeded'), (4, 'Runtime Error'), (5, 'Output Format Error'), (6, 'Memory Limit Exceeded'), (7, 'Rejected'), (8, 'Compilation Error'), (9, 'Command Executing Error'), (10, 'Idleness Limit Exceeded'), (11, 'Syntax Error'), (12, 'Checker Not Found'), (13, 'Only Python'), (14, 'Object Not Found'), (15, 'Fake Accepted'), (16, 'Partial Solution'), (17, 'Not Available Language')], default=-2)),
                ('lang', models.CharField(choices=[('py', 'Python'), ('cpp', 'Cpp'), ('r', 'R'), ('hs', 'Haskell'), ('kt', 'Kotlin'), ('c', 'C'), ('text', 'Text'), ('kep', 'Kep')], max_length=10)),
                ('test_case_number', models.IntegerField(default=1, null=True)),
                ('time', models.PositiveIntegerField(default=0)),
                ('memory', models.PositiveIntegerField(default=0)),
                ('source_code', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='backend.problem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
