# Generated by Django 4.0.4 on 2023-05-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
