# Generated by Django 4.0.4 on 2023-05-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_problem_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='source_code',
        ),
    ]
